name: Build and Deploy with Run Number Versioning

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:  
    name: Build and Push
    runs-on: ubuntu-latest
    steps:  

    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true

    - name: Build Docker Image (use run number for version)
      run: docker-compose build --build-arg VERSION=${{ github.run_number }}  # Use run number as version

    - name: Push to AR
      run: docker push asia-southeast1-docker.pkg.dev/cw-devops/mh-test/gitbook:${{ github.run_number }}