name: Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:  
    name: Build and Push
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: gitbook
      PROJECT_ID: cw-devops
    steps:  

    - name: code checkout
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: gcloud login
      run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

    - name: Push to AR
      run: docker push asia-southeast1-docker.pkg.dev/$PROJECT_ID/mh-test/$IMAGE_NAME:latest