name: Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:  
    name: Build and Push
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: cw-devops
    steps:  

    - name: code checkout
      uses: actions/checkout@v2

    - id: "auth"
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      
    - name: Build Docker Image
      run: docker-compose build

    - name: gcloud auth
      run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

    - name: Push to AR
      run: docker push asia-southeast1-docker.pkg.dev/$PROJECT_ID/mh-test/gitbook:latest