name: Build and Deploy with Run Number Versioning

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:  
    name: Build and Push
    runs-on: ubuntu-latest
    steps:  

    - name: code checkout
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Build Docker Image (use run number for version)
      run: docker-compose build

    - name: gcloud login
      run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev

    - name: Push to AR
      run: docker push asia-southeast1-docker.pkg.dev/cw-devops/mh-test/gitbook:latest